service:
  web:
    build:
      context: ./mysite/
      command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mysite/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./env/dev.env

  nginx:
    build:
      context: .
    ports:
      - 8000:80
    volumes:
      - ./html/:/usr/share/ngpoinx/html/
      - ./conf.d/:/etc/nginx/conf.d/
  dns:
    build:
      context: ./dns/
    restart: always
    ports:
      - 53:53
      - 53:53/udp
    volumes:
      - ./dns/named.conf:/ect/bind/named.conf
      - ./dns/zone/:/etc/bind/zone/
    command: named -c /etc/bind/named.conf -g -u named